### ISSUE TITLE
Implement plotly into HTML 

### ISSUE THREAD

**Issue by kossakova** [HotMochaNoWhip/Vitamin_Ventures#10]

**Comment by HollyC13** [comment]
Interactive Plotly graph created in Jupyter Notebooks deployed to html webpage.  We can review on our call tonight to determine if we are ready to close this issue.

![SampleDeploy1](https://user-images.githubusercontent.com/88636336/149670667-c5252c52-52c4-4ba2-a722-089688374c7c.png)

**Comment by kossakova** [comment]
@HollyC13 can you create a branch (or update static_site that Linnea created earlier) and share files, whenever we compile the task we can merge them to the main branch

**Comment by HollyC13** [comment]
@kossakova File is uploaded to static_site:  image.html.  Line 35 is where the Plotly chart is added to the website as a html file.  The html file is created by code in the file creating the Plotly chart.

**Comment by kossakova** [comment]
Complited
